version: "3.2"
services:
  api:
    user: ${UID}:${GID}
    image: ml_api
    build:
      args:
        - UID=${UID}
        - GID=${GID}
      context: ./api
      target: build
    ports:
      - "80:5000"
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    depends_on:
      - redis
      - model
    volumes:
      - ./feedback:/src/feedback
      - ./uploads:/src/static/uploads

  redis:
    image: redis:latest

  model:
    user: ${UID}:${GID}
    image: ml_services
    build:
      args:
        - UID=${UID}
        - GID=${GID}
      context: ./model
      target: build
    depends_on:
      - redis
    volumes:
      - ./uploads:/src/uploads
